### ISSUE TITLE
Allow Discord Rich Presence to be optional?

### ISSUE THREAD

**Issue by FloatingMilkshake** [spotlightishere/Ongaku#12]
Currently Ongaku always displays a Discord Rich Presence with the currently playing music. Last.fm scrobbling is optional, but Discord presence isn't; it would be nice if Discord presence was also optional! Sometimes I want to scrobble to Last.fm without also displaying my activity on Discord.

**Comment by MCMi460** [comment]
This has been added in #15, 825d802b95fd608909d4df8b3a3f5142e108b63c.
